flaskblog/models.py
from datetime import datetime
from flask.json import jsonify
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
from flask import current_app, request, jsonify, session
from werkzeug.wrappers import auth
from flaskblog.config import Config
from flaskblog import db, login_manager
from flask_login import UserMixin
from functools import wraps 
import jwt


followers = db.Table('followers',
                    db.Column('follower_id', db.Integer, db.ForeignKey('user.id')),
                    db.Column('followed_id', db.Integer, db.ForeignKey('user.id'))
)


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(20), unique=True, nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)
    # image_file = db.Column(db.String(20), nullable=False, default='default.jpg')
    password = db.Column(db.String(100), nullable=False)
    posts = db.relationship('Post', backref='author', lazy=True)
    liked = db.relationship('PostLike', foreign_keys='PostLike.user_id', backref='user', lazy='dynamic')
    comments = db.relationship('Comment', backref='user', lazy=True)
    followed = db.relationship('User',
                               secondary=followers,
                               primaryjoin=(followers.c.follower_id == id),
                               secondaryjoin=(followers.c.followed_id == id),
                               backref=db.backref('followers', lazy='dynamic'),
                               lazy='dynamic')

    def follow(self, user):
        if not self.is_following(user):
            self.followed.append(user)
            return self

    def unfollow(self, user):
        if self.is_following(user):
            self.followed.remove(user)
            return self

    def is_following(self, user):
        return self.followed.filter(followers.c.followed_id == user.id).count() > 0

    def followed_posts(self):
        return Post.query.join(followers, (followers.c.followed_id == Post.user_id)).filter(followers.c.follower_id == self.id).order_by(Post.date_posted.desc())

    def like_post(self, post):
        if not self.has_liked_post(post):
            like = PostLike(user_id=self.id, post_id=post.id)
            db.session.add(like)

    def unlike_post(self, post):
        if self.has_liked_post(post):
            PostLike.query.filter_by(user_id=self.id, post_id=post.id).delete()

    def has_liked_post(self, post):
        return PostLike.query.filter(PostLike.user_id == self.id, PostLike.post_id == post.id).count() > 0


    @staticmethod
    def decode_auth_token():
        """
        Decodes the auth token
        :param auth_token:
        :return: integer|string
        """
        try:
            # if 'X-API-KEY' in request.headers:
            #     auth_token = request.headers['X-API-KEY']
            if 'token' in session:
                s = session['token']
                session.pop('token', None)
                return jsonify({'message': 'You are suceesfuly loged out, Thank You.'})
            return jsonify({'message': 'You are not loged out, Sorry!!'})

            # payload = jwt.decode(auth_token, Config.SECRET_KEY)
            # response_object = {
            #             'status': 'success',
            #             'message': 'Successfully logged out.',
            #             'Authorization': payload
            # }
            # return jsonify(response_object)
        except jwt.ExpiredSignatureError:
            return 'Signature expired. Please log in again.'
        except jwt.InvalidTokenError:
            return 'Invalid token. Please log in again.'


    def __repr__(self):
        return f"User('{self.username}', '{self.email}')"


class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(100), nullable=False)
    date_posted = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    content = db.Column(db.Text, nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    likes = db.relationship('PostLike', backref='post', lazy='dynamic')
    comments = db.relationship('Comment', backref='article', lazy='dynamic')
    updated_date = db.Column(db.DateTime, nullable=True)

    def get_comments(self):
        return Comment.query.filter_by(post_id=post.id).order_by(Comment.timestamp.desc())

    def __repr__(self):
        return f"Post('{self.title}', '{self.date_posted}')"


class PostLike(db.Model):
    __tablename__ = 'post_like'
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    post_id = db.Column(db.Integer, db.ForeignKey('post.id'))


class Comment(db.Model):
    __tablename__ = 'comment'
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    post_id = db.Column(db.Integer, db.ForeignKey('post.id'), nullable=False)
    body = db.Column(db.String(100), nullable=False)
    created_date = db.Column(db.DateTime, default=datetime.utcnow)

    def __repr__(self):
        return f"Comment('{self.body}')"

def token_required(f):
    @wraps(f)
    def decorator(*args, **kwargs):
        # token = None

        # if 'X-API-KEY' in request.headers:
        #     token = request.headers['X-API-KEY']
        if 'token' in session:
            token = session['token']

        else:
            return jsonify({'message': 'Already loged out, Please log in again.'})

        try:
            data = jwt.decode(token, Config.SECRET_KEY)
            current_user = User.query.filter_by(id=data['public_id']).first()
        except:
            return jsonify({'message': 'Invalid token.'})

        return f(current_user, *args, **kwargs)
    return decorator

flaskblog/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')


class AddCommentForm(FlaskForm):
    body = StringField("Body", validators=[DataRequired()])
    submit = SubmitField("Post")

flaskblog/posts/routes.py
from flask import (request, Blueprint, jsonify)
from flaskblog import db
from flaskblog.models import Comment, Post, token_required
from datetime import datetime
from flaskblog.users.utils import get_a_post, get_all_posts

posts = Blueprint('posts', __name__)


@posts.route("/posts/new_post", methods=['GET', 'POST'])
@token_required
def new_post(current_user):
    post = Post.query.filter_by(title=request.json.get('title')).first()
    if not post:
        new_post = Post(
            title=request.json.get('title'),
            content=request.json.get('content'),
            user_id=current_user
        )
        db.session.add(new_post)
        db.session.commit()
        response_object = {
            'status': 'success',
            'message': 'Your post is created.',
        }
        return jsonify(response_object)


@posts.route("/posts/<int:id>", methods=['GET', 'POST'])
@token_required
def post(current_user, id):
    post = get_a_post(id)
    comment = Comment(
        body=request.json.get('body'),
        post_id=id,
        user_id=current_user.id
    )
    db.session.add(comment)
    db.session.commit()
    comments = db.session.query(Comment).filter(Comment.post_id == id).all()
    if not post:
        posts.abort(404)
    elif comments:
        response_data = {
            'status': 'success',
            'message': 'You have commented on post'
        }
        return jsonify(response_data)
    return post


@posts.route("/posts/list", methods=['GET', 'POST'])
def all_post():
    posts = get_all_posts()
    return jsonify(posts)


@posts.route("/posts/<int:post_id>/update", methods=['GET', 'POST'])
@token_required
def update_post(a, post_id):
    post = Post.query.filter_by(id=post_id).first()
    if post:
        post.title=request.json.get('title'),
        post.content=request.json.get('content'),
        post.id=request.json.get('id'),
        post.updated_date = datetime.utcnow()
        db.session.commit()
        response_object = {
            'status': 'success',
            'message': 'Your post is updated.',
        }
    return jsonify(response_object)


@posts.route("/posts/<int:post_id>/delete", methods=['POST'])
@token_required
def delete_post(a, post_id):
    post = Post.query.filter_by(id=post_id).first()
    db.session.delete(post)
    db.session.commit()
    response_object = {
        'status': 'success',
        'message': 'Your post is deleted.',
    }
    return jsonify(response_object)


@posts.route('/posts/like_unlike/<int:user_id>/<int:post_id>/<action>')
@token_required
def like_action(current_user, user_id, post_id, action):
    post = Post.query.filter_by(id=post_id).first()
    post.likes.count()

    if action == 'like':
        current_user.like_post(post)
        db.session.commit()

    if action == 'unlike':
        current_user.unlike_post(post)
        db.session.commit()
    
    data = {'count': post.likes.count(), 'action': action}
    return jsonify(data)


@posts.route("/posts/post_comment/<int:comment_id>/delete", methods=['GET', 'POST'])
@token_required
def delete_comment(a, comment_id):
    comments = Comment.query.filter_by(id=comment_id).first()
    db.session.delete(comments)
    db.session.commit()
    response_data = {
        'status': 'Sucess',
        'message':'Your comment has been deleted!'
    }
    return jsonify(response_data)

flaskblog/users/routes.py
from flask import request, Blueprint, jsonify
from flaskblog import db, bcrypt
from flaskblog.models import User, token_required
from .auth_helper import Auth
from .utils import get_all_users, get_a_user, getOtpApi
import validators
from .forms import RegistrationForm
from flask import session
from werkzeug.security import generate_password_hash

users = Blueprint('users', __name__)


@users.route("/users/register", methods=['GET', 'POST'])
def register():
    req = request.get_json()
    form = RegistrationForm().from_json(req)
    if not form.validate():
        # if len(new_user.password) < 6:
        #     return jsonify({'error': "Password is too short"})
        # if len(new_user.username) < 3:
        #     return jsonify({"error": "Username is too short"})
        # if not new_user.username.isalnum() or " " in new_user.username:
        #     return jsonify({"error": "Username should be alphanumeric, also no spaces"})
        # if not validators.email(new_user.email):
        #     return jsonify({"error": "Email is not valid"})
        # if User.query.filter_by(username=request.json.get('username')).first():
        #     return jsonify({"error": "Username is taken"})
        # if User.query.filter_by(email=request.json.get('email')).first():
        #     return jsonify({"error": "Email is taken"})
        response_object = {
            'status': 'danger',
            'message': form.errors
        }
        return response_object
    hashed_password = generate_password_hash(form.password.data)
    new_user = User(username=form.username.data, email=form.email.data, password=hashed_password)
    db.session.add(new_user)
    db.session.commit()
    response_object = {
        'status': 'success',
        'message': 'User created',
    }
    return response_object


@users.route('/users/list', methods=['GET', 'POST'])
@token_required
def list_of_all_users(a):
    user_list = get_all_users()
    return jsonify(user_list)


@users.route('/users/user_profile/<int:user_id>', methods=['GET', 'POST'])
def user_profile(user_id=None):
    """get a user given its identifier"""
    user = get_a_user(user_id)
    if not user:
        users.abort(404)
    else:
        return user


@users.route("/users/login", methods=['GET', 'POST'])
def login():
    return Auth.login_user()


@users.route("/users/logout")
def logout():
    return Auth.logout_user()


@users.route("/users/account/<int:user_id>/update", methods=['GET', 'POST'])
@token_required
def account(a, user_id=None):
    user = User.query.filter_by(id=user_id).first()
    if user:
        user.username=request.json.get('username'),
        user.email=request.json.get('email'),
        user.id=request.json.get('id'),
        user.password=request.json.get('password')
        db.session.commit()
        response_object = {
            'status': 'success',
            'message': 'Your account is updated.',
        }
        return jsonify(response_object)


@users.route('/users/follow/<username>')
@token_required
def follow(current_user, username):
    user = User.query.filter_by(username=username).first()
    if user is None:
        response_data = {
            'status': 'danger',
            'message': 'User %s not found.' % username
        }
        return response_data
    if user == current_user:
        response_data = {
            'status': 'danger',
            'message': 'You can\'t follow yourself!'
        }
        return response_data
    u = current_user.follow(user)
    if u is None:
        response_data = {
            'status': 'danger',
            'message': 'Cannot follow ' + username + '.'
        }
        return response_data
    db.session.add(u)
    db.session.commit()
    response_data = {
        'status': 'success',
        'message': 'You are now following ' + username + '!'
    } 
    return response_data


@users.route('/users/unfollow/<username>')
@token_required
def unfollow(current_user, username):
    user = User.query.filter_by(username=username).first()
    if user is None:
        response_data = {
            'status': 'danger',
            'message': 'User %s not found.' % username
        }
        return response_data
    if user == current_user:
        response_data = {
            'status': 'danger',
            'message': 'You can\'t unfollow yourself!'
        }
        return response_data
    u = current_user.unfollow(user)
    if u is None:
        response_data = {
            'status': 'danger',
            'message': 'Cannot unfollow ' + username + '.'
        }
        return response_data
    db.session.add(u)
    db.session.commit()
    response_data = {
        'status': 'success',
        'message': 'You have stopped following ' + username + '.'
    } 
    return response_data


@users.route("/users/user_list_followers/<username>")
@token_required
def listFollowers(a, username):
    user = User.query.filter_by(username=username).first_or_404()
    user_followers = user.followers.all()
    response_data = {
        'status': 'success',
        'message': 'Your followers list is: ' + str(user_followers) + '.'
    } 
    return response_data


@users.route("/users/user_list_following/<username>")
@token_required
def listFollowing(a, username):
    user = User.query.filter_by(username=username).first_or_404()
    user_following = user.followed.all()
    response_data = {
        'status': 'success',
        'message': 'Your following list is: ' + str(user_following) + '.'
    } 
    return response_data


@users.route("/users/follower/<int:user_id>/delete", methods=['GET', 'POST'])
@token_required
def removeFollower(current_user, user_id):
    user = User.query.filter_by(id=user_id).first_or_404()
    unfollow = user.unfollow(current_user)
    db.session.add(unfollow)
    db.session.commit()
    response_data = {
        'status': 'success',
        'message': 'Your follower has been removed!'
    } 
    return response_data


@users.route("/users/get_otp", methods=['POST'])
def get_otp():
    num = request.json.get('number')
    val = getOtpApi(num)
    if val:
        return jsonify({'message': 'otp sent in your mobile number'})


@users.route('/users/validateOtp', methods=['POST'])
def validateOtp():
    otp = request.json.get('otp')
    if 'response' in session:
        s = session['response']
        session.pop('response', None)
        if s == otp:
            return jsonify({'message': 'You are Authorized, Thank You.'})
        else:
            return jsonify({'message': 'You are not Authorized, Sorry!!'})
    return jsonify({"message": "Sorry, OTP expired please resend the otp."})

flaskblog/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href='https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css'>
    <link rel="stylesheet" href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css'>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='like_post.css') }}">

    {% if title %}
        <title>Flask Blog - {{ title }}</title>
    {% else %}
        <title>Flask Blog</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
        <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
          <div class="container">
            <a class="navbar-brand mr-4" href="/">Flask Blog</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
              <div class="navbar-nav mr-auto">
                <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
              </div>
              <!-- Navbar Right Side -->
              <div class="navbar-nav">
                {% if current_user.is_authenticated %}
                  <a class="nav-item nav-link" style="margin-left: 200px;" href="{{ url_for('posts.followed_posts') }}">Feed</a>
                  <a class="nav-item nav-link" href="{{ url_for('posts.new_post') }}">New Post</a>
                  <a class="nav-item nav-link" href="{{ url_for('users.user_profile', user_id=current_user.id) }}">{{ current_user.username }}</a>
                  <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
                {% else %}
                  <a class="nav-item nav-link" style="margin-left: 200px;" href="{{ url_for('users.login') }}">Login</a>
                  <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
                {% endif %}
                {% block search %}{% endblock %}
              </div>
            </div>
          </div>
        </nav>
      </header>
      <main role="main" class="container">
        {% block filter %}{% endblock %}
        <br>
        <div class="row">
          <div class="col-md-8">
            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    {% for category, message in messages %}
                        <div class="alert alert-{{ category }}">
                        {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
            {% endwith %}
            {% block content %}{% endblock %}
          </div>
        </div>
      </main>
    <!-- Option 1: Bootstrap Bundle with Popper -->
    
    <script src='https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js'></script>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js'></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="{{ url_for('static', filename='jquery-3.6.0.js') }}"></script>
    {% block js %}{% endblock %}
</body>
</html>

flaskblog/templates/post.html
{% extends "layout.html" %}
{% block content %}
  <article class="media content-section">
    <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
    <div class="media-body">
      <div class="article-metadata pt-4">
        <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a><br>
		<small class="text-muted">created_date {{ post.date_posted.strftime('%Y-%m-%d') }}</small><br>
		<small class="text-muted">updated_date {{ post.updated_date }}</small>
        {% if post.author == current_user %}
          <div><br>
            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('posts.update_post', post_id=post.id) }}">Update</a>
            <button type="button" class="btn btn-danger btn-sm m-1" data-bs-toggle="modal" data-bs-target="#deleteModal">Delete</button>
          </div><br>
        {% endif %}
      </div>
      <h2 class="article-title">{{ post.title }}</h2>
      <p class="article-content">{{ post.content }}</p>
	  <div class="d-flex flex-row fs-11 mt-2">
		{% if current_user.is_authenticated %}
		{% if current_user.has_liked_post(post) %}
		  <a class="like p-1 cursor" href="{{ url_for('posts.like_action', post_id=post.id, action='unlike') }}"><i class="fa fa-heart"></i><span class="ml-1">Unlike</span></a>
		{% else %}
		  <a class="like p-1 cursor" href="{{ url_for('posts.like_action', post_id=post.id, action='like') }}"><i class="fa fa-heart-o"></i><span class="ml-1">Like</span></a>
		{% endif %}
		{% endif %}
		<div class="like p-1 cursor mr-2">{{ post.likes.count() }} likes</div>
    <div class="like p-1 cursor mr-2">{{ post.comments.count() }} comments</div>
		</div>
    </div>
  </article>
  <div class="content-section">
    <form method="POST" action="">
      {{ form.hidden_tag() }}
      <fieldset class="form-group">
          <legend class="border-bottom mb-4">Comment</legend>
          <div class="form-group">
              {% if form.body.errors %}
                  {{ form.body(class="form-control form-control-lg is-invalid") }}
                  <div class="invalid-feedback">
                      {% for error in form.body.errors %}
                          <span>{{ error }}</span>
                      {% endfor %}
                  </div>
              {% else %}
                  {{ form.body(class="form-control form-control-l") }}
              {% endif %}
          </div>
      </fieldset>
      <div class="form-group">
          {{ form.submit(class="btn btn-outline-info") }}
      </div>
  </form>
  </div>
  {% if post.comments %}
  <legend class="border-bottom mb-4">All Comments</legend>
  {% for comment in comments %}
  <article class="media content-section">
    <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + comment.user.image_file) }}">
    <div class="media-body">
      <div class="article-metadata pt-4">
        <a class="mr-2" href="{{ url_for('users.user_posts', username=comment.user.username) }}">{{ comment.user.username }}</a>
        <h5 id="user-comment" class="media-body">{{ comment.body }}</h5>
        <small class="text-muted">{{ comment.created_date }}</small>
        <form action="" method="GET">
          <a class="mr-2" href="{{ url_for('posts.delete_comment', comment_id=comment.id) }}" onclick="if (!confirm('Are you sure you want to delete?')) { return false }"><i class="fa fa-trash" aria-hidden="true"></i> Delete</a>
        </form>
      </div>
    </div>
  </article>
  {% endfor %}
  {% else %}
  <div class="border-top text-center font-weight-bold">No comments yet</div>
  {% endif %}
  <!-- Modal -->
  <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Are you sure you want to delete this post?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
            <input class="btn btn-danger" type="submit" value="Delete">
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

flaskblog/templates/search.html
{% extends 'layout.html' %}
{% set page_title = 'Search' %}
{% block body %}
    <div>
        {{ render_form(url_for('search'), form) }} # note: render_form is some marco from another .html file
    </div>
{% endblock %}

flaskblog/templates/user_profile.html
{% extends "layout.html" %}
{% block content %}
{% if user == current_user %}
<div class="content-section">
    <div class="media">
        <img class="rounded-circle account-img" src="{{ url_for('static', filename='profile_pics/' + current_user.image_file) }}" alt="Profile Image">
        <div class="media-body">
            <h2 class="account-heading">{{ current_user.username }}</h2>
            <p class="text-secondary">{{ current_user.email }}</p>
            <a class="mr-2" href="{{ url_for('users.listFollowers', username=user.username)}}">{{ user.followers.count() }} followers</a>, <a class="mr-2" href="{{ url_for('users.listFollowing', username=user.username)}}">{{ user.followed.count() }} following.</a><br><br>
            <a href="{{ url_for('users.account') }}" class="btn btn-outline-info">Edit Profile</a>
		</div>
    </div>
</div>
{% if user_followers %}
<legend class="border-bottom mb-4">Followers</legend>
<div class="table-responsive-md">
    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th scope="col">Username</th>
                <th scope="col" style="margin-right: 5px;">Action</th>
            </tr>
        </thead>
        {% for users in user_followers %}
        <tbody>
            <tr>
                <td>
                    <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + users.image_file) }}" alt="Profile Image">
                    <a class="mr-2" href="{{ url_for('users.user_profile', user_id=users.id) }}">{{ users.username }}</a>
                </td>
                <td>
                    <form action="{{ url_for('users.removeFollower', user_id=users.id) }}" method="GET">
                        <button class="btn btn-outline-danger" onclick="if (!confirm('Are you sure you want to remove this follower?')) { return false }">Remove</button>
                    </form>
                </td>
            </tr>
        </tbody>
        {% endfor %}
    </table>
</div>
{% elif user_following %}
<legend class="border-bottom mb-4">Following</legend>
<div class="table-responsive-md">
    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th scope="col">Username</th>
                <th scope="col" style="margin-right: 5px;">Action</th>
            </tr>
        </thead>
        <tbody>
            {% for users in user_following %}
            <tr>
                <td>
                    <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + users.image_file) }}" alt="Profile Image">
                    <a class="mr-2" href="{{ url_for('users.user_profile', user_id=users.id) }}">{{ users.username }}</a>
                </td>
                <td>
                    <div class="d-flex flex-row align-items-center mt-2">
                        <a class="btn btn-outline-primary" href="{{ url_for('users.unfollow', username=users.username) }}" onclick="if (!confirm('Are you sure you want to unfollow?')) { return false }">Unfollow</a>
                    </div>    
                </td>
            </tr>
            {% endfor %}
        </tbody>
        
    </table>
</div>
{% endif %}
{% else %}
<div class="content-section">
    <div class="media">
        <img class="rounded-circle account-img" src="{{ url_for('static', filename='profile_pics/' + user.image_file) }}" alt="Profile Image">
        <div class="media-body">
            <h2 class="account-heading">{{ user.username }}</h2>
            <p class="text-secondary">{{ user.email }}</p>
            <p>{{ user.followers.count() }} followers, {{ user.followed.count() }} following.</p>
            {% if not current_user.is_following(user) %}
                <a href="{{ url_for('users.follow', username=user.username) }}">Follow</a>
            {% else %}
                <a href="{{ url_for('users.unfollow', username=user.username) }}">Unfollow</a>
            {% endif %}
		</div>
    </div>
</div>
{% endif %}
{% endblock %}